<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Enums\Character\CharacterSexEnum;

class CharacterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('characters')->insert([
            [
                'name' => 'Clark Kent',
                'codename' => 'Superman',
                'sex' => CharacterSexEnum::MALE,
                'age' => '25',
                'avatar' => '',
                'weakness' => 'Kriptonita',
                'affiliate' => 'Kara Zor-El',
                'pair' => 'Lois Lane',
                'planet' => 'Terra',
                'city' => 'Metrópolis',
                'team_id' => 1,
                'squad_id' => null,
            ],
            [
                'name' => 'Diana Price',
                'codename' => 'Mulher Maravilha',
                'sex' => CharacterSexEnum::FEMALE,
                'age' => '150',
                'avatar' => '',
                'weakness' => 'Magia',
                'affiliate' => 'Hipólita',
                'pair' => 'Steve Trevor',
                'planet' => 'Terra',
                'city' => 'Temyscera',
                'team_id' => 1,
                'squad_id' => null,
            ],
            [
                'name' => 'Bruce Wayne',
                'codename' => 'Batman',
                'sex' => CharacterSexEnum::MALE,
                'age' => '29',
                'avatar' => '',
                'weakness' => 'Combate, estratégia',
                'affiliate' => 'Alfred',
                'pair' => 'Selina Kyle',
                'planet' => 'Terra',
                'city' => 'Gotham',
                'team_id' => 1,
                'squad_id' => null,
            ],
            [
                'name' => 'Barry Allen',
                'codename' => 'Flash',
                'sex' => CharacterSexEnum::MALE,
                'age' => '29',
                'avatar' => '',
                'weakness' => 'Combate, estratégia',
                'affiliate' => 'Alfred',
                'pair' => 'Selina Kyle',
                'planet' => 'Terra',
                'city' => 'Gotham',
                'team_id' => 1,
                'squad_id' => null,
            ],
            [
                'name' => 'Hal Jordan',
                'codename' => 'Lanterna Verde',
                'sex' => CharacterSexEnum::MALE,
                'age' => '30',
                'avatar' => '',
                'weakness' => 'Medo',
                'affiliate' => 'Sinestro',
                'pair' => 'Carol Ferris',
                'planet' => 'Terra',
                'city' => 'Coast City',
                'team_id' => 1,
                'squad_id' => null,
            ],
            [
                'name' => 'Arthur Curry',
                'codename' => 'Aquaman',
                'sex' => CharacterSexEnum::MALE,
                'age' => '32',
                'avatar' => '',
                'weakness' => 'Desidratação',
                'affiliate' => 'Mera',
                'pair' => 'Mera',
                'planet' => 'Terra',
                'city' => 'Atlantis',
                'team_id' => 1,
                'squad_id' => null,
            ],
            [
                'name' => 'Victor Stone',
                'codename' => 'Cyborg',
                'sex' => CharacterSexEnum::MALE,
                'age' => '25',
                'avatar' => '',
                'weakness' => 'Ataques cibernéticos',
                'affiliate' => 'Silas Stone',
                'pair' => null,
                'planet' => 'Terra',
                'city' => 'Detroit',
                'team_id' => 3,
                'squad_id' => null,
            ],
            [
                'name' => 'Billy Batson',
                'codename' => 'Shazam',
                'sex' => CharacterSexEnum::MALE,
                'age' => '14',
                'avatar' => '',
                'weakness' => 'Magia poderosa',
                'affiliate' => 'Freddy Freeman',
                'pair' => null,
                'planet' => 'Terra',
                'city' => 'Fawcett City',
                'team_id' => 1,
                'squad_id' => null,
            ],
            [
                'name' => 'John Stewart',
                'codename' => 'Lanterna Verde',
                'sex' => CharacterSexEnum::MALE,
                'age' => '35',
                'avatar' => '',
                'weakness' => 'Medo',
                'affiliate' => 'Guardians of the Universe',
                'pair' => null,
                'planet' => 'Terra',
                'city' => 'Coast City',
                'team_id' => 6,
                'squad_id' => null,
            ],
            [
                'name' => 'Zatanna Zatara',
                'codename' => 'Zatanna',
                'sex' => CharacterSexEnum::FEMALE,
                'age' => '28',
                'avatar' => '',
                'weakness' => 'Perda de voz',
                'affiliate' => 'Giovanni Zatara',
                'pair' => null,
                'planet' => 'Terra',
                'city' => 'Nova York',
                'team_id' => 1,
                'squad_id' => null,
            ],
            [
                'name' => "J'onn J'onzz",
                'codename' => 'Caçador de Marte',
                'sex' => CharacterSexEnum::MALE,
                'age' => 'Marte',
                'avatar' => '',
                'weakness' => 'Fogo',
                'affiliate' => 'Liga da Justiça',
                'pair' => null,
                'planet' => 'Marte',
                'city' => 'Marte',
                'team_id' => 1,
                'squad_id' => null,
            ],
            [
                'name' => 'Oliver Queen',
                'codename' => 'Arqueiro Verde',
                'sex' => CharacterSexEnum::MALE,
                'age' => '35',
                'avatar' => '',
                'weakness' => 'Combate corpo a corpo',
                'affiliate' => 'Roy Harper',
                'pair' => 'Dinah Lance',
                'planet' => 'Terra',
                'city' => 'Star City',
                'team_id' => 1,
                'squad_id' => null,
            ],
            [
                'name' => 'Kara Zor-El',
                'codename' => 'Supergirl',
                'sex' => CharacterSexEnum::FEMALE,
                'age' => '24',
                'avatar' => '',
                'weakness' => 'Kriptonita',
                'affiliate' => 'Clark Kent',
                'pair' => null,
                'planet' => 'Terra',
                'city' => 'National City',
                'team_id' => 10,
                'squad_id' => null,
            ],
            [
                'name' => 'Dinah Lance',
                'codename' => 'Canário Negro',
                'sex' => CharacterSexEnum::FEMALE,
                'age' => '30',
                'avatar' => '',
                'weakness' => 'Vulnerável a armas de fogo',
                'affiliate' => 'Oliver Queen',
                'pair' => 'Oliver Queen',
                'planet' => 'Terra',
                'city' => 'Star City',
                'team_id' => 13,
                'squad_id' => null,
            ]
        ]);
    }
}
