<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Enums\Character\CharacterSexEnum;

class CharacterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('characters')->insert([[
                'name' => 'Clark Kent',
                'codename' => 'Superman',
                'sex' => CharacterSexEnum::MALE,
                'age' => '25',
                'avatar' => 'http://myapp.local:8000/storage/public/images/heroes/1721663334.png',
                'affiliate' => 'Kara Zor-El',
                'pair' => 'Lois Lane',
                'planet' => 'Terra',
                'city' => 'Metrópolis',
                'team_id' => 1,
                'squad_id' => null,
                'color' => '#0F52BA',
            ],
            [
                'name' => 'Diana Price',
                'codename' => 'Mulher Maravilha',
                'sex' => CharacterSexEnum::FEMALE,
                'age' => '150',
                'avatar' => 'http://myapp.local:8000/storage/public/images/heroes/1721666005.png',
                'affiliate' => 'Hipólita',
                'pair' => 'Steve Trevor',
                'planet' => 'Terra',
                'city' => 'Temyscera',
                'team_id' => 1,
                'squad_id' => null,
                'color' => '#C8102E',
            ],
            [
                'name' => 'Bruce Wayne',
                'codename' => 'Batman',
                'sex' => CharacterSexEnum::MALE,
                'age' => '29',
                'avatar' => 'http://myapp.local:8000/storage/public/images/heroes/1721666043.png',
                'affiliate' => 'Alfred',
                'pair' => 'Selina Kyle',
                'planet' => 'Terra',
                'city' => 'Gotham',
                'team_id' => 1,
                'squad_id' => null,
                'color' => '#000000',
            ],
            [
                'name' => 'Barry Allen',
                'codename' => 'Flash',
                'sex' => CharacterSexEnum::MALE,
                'age' => '29',
                'avatar' => 'http://myapp.local:8000/storage/public/images/heroes/1721666059.png',
                'affiliate' => 'Alfred',
                'pair' => 'Selina Kyle',
                'planet' => 'Terra',
                'city' => 'Gotham',
                'team_id' => 1,
                'squad_id' => null,
                'color' => '#FF0000',
            ],
            [
                'name' => 'Hal Jordan',
                'codename' => 'Lanterna Verde',
                'sex' => CharacterSexEnum::MALE,
                'age' => '30',
                'avatar' => 'http://myapp.local:8000/storage/public/images/heroes/1721666165.png',
                'affiliate' => 'Sinestro',
                'pair' => 'Carol Ferris',
                'planet' => 'Terra',
                'city' => 'Coast City',
                'team_id' => 1,
                'squad_id' => null,
                'color' => '#00FF00',
            ],
            [
                'name' => 'Arthur Curry',
                'codename' => 'Aquaman',
                'sex' => CharacterSexEnum::MALE,
                'age' => '32',
                'avatar' => 'http://myapp.local:8000/storage/public/images/heroes/1721666253.png',
                'affiliate' => 'Mera',
                'pair' => 'Mera',
                'planet' => 'Terra',
                'city' => 'Atlantis',
                'team_id' => 1,
                'squad_id' => null,
                'color' => '#0082FC',
            ],
            [
                'name' => 'Victor Stone',
                'codename' => 'Cyborg',
                'sex' => CharacterSexEnum::MALE,
                'age' => '25',
                'avatar' => 'http://myapp.local:8000/storage/public/images/heroes/1721666297.png',
                'affiliate' => 'Silas Stone',
                'pair' => null,
                'planet' => 'Terra',
                'city' => 'Detroit',
                'team_id' => 3,
                'squad_id' => null,
                'color' => '#8B8B8B',
            ],
            [
                'name' => 'Billy Batson',
                'codename' => 'Shazam',
                'sex' => CharacterSexEnum::MALE,
                'age' => '14',
                'avatar' => 'http://myapp.local:8000/storage/public/images/heroes/1721666395.png',
                'affiliate' => 'Freddy Freeman',
                'pair' => null,
                'planet' => 'Terra',
                'city' => 'Fawcett City',
                'team_id' => 1,
                'squad_id' => null,
                'color' => '#F7E03C',
            ],
            [
                'name' => 'John Stewart',
                'codename' => 'Lanterna Verde',
                'sex' => CharacterSexEnum::MALE,
                'age' => '35',
                'avatar' => 'http://myapp.local:8000/storage/public/images/heroes/1721666448.png',
                'affiliate' => 'Guardians of the Universe',
                'pair' => null,
                'planet' => 'Terra',
                'city' => 'Coast City',
                'team_id' => 6,
                'squad_id' => null,
                'color' => '#00FF00',
            ],
            [
                'name' => 'Zatanna Zatara',
                'codename' => 'Zatanna',
                'sex' => CharacterSexEnum::FEMALE,
                'age' => '28',
                'avatar' => 'http://myapp.local:8000/storage/public/images/heroes/1721666521.png',
                'affiliate' => 'Giovanni Zatara',
                'pair' => null,
                'planet' => 'Terra',
                'city' => 'Nova York',
                'team_id' => 1,
                'squad_id' => null,
                'color' => '#6A0D91',
            ],
            [
                'name' => "J'onn J'onzz",
                'codename' => 'Caçador de Marte',
                'sex' => CharacterSexEnum::MALE,
                'age' => '150',
                'avatar' => 'http://myapp.local:8000/storage/public/images/heroes/1721666582.png',
                'affiliate' => 'Liga da Justiça',
                'pair' => null,
                'planet' => 'Marte',
                'city' => 'Marte',
                'team_id' => 1,
                'squad_id' => null,
                'color' => '#FF4500',
            ],
            [
                'name' => 'Oliver Queen',
                'codename' => 'Arqueiro Verde',
                'sex' => CharacterSexEnum::MALE,
                'age' => '35',
                'avatar' => 'http://myapp.local:8000/storage/public/images/heroes/1721666678.png',
                'affiliate' => 'Roy Harper',
                'pair' => 'Dinah Lance',
                'planet' => 'Terra',
                'city' => 'Star City',
                'team_id' => 1,
                'squad_id' => null,
                'color' => '#006400',
            ],
            [
                'name' => 'Kara Zor-El',
                'codename' => 'Supergirl',
                'sex' => CharacterSexEnum::FEMALE,
                'age' => '24',
                'avatar' => 'http://myapp.local:8000/storage/public/images/heroes/1721666743.png',
                'affiliate' => 'Clark Kent',
                'pair' => null,
                'planet' => 'Terra',
                'city' => 'National City',
                'team_id' => 10,
                'squad_id' => null,
                'color' => '#0F52BA',
            ],
            [
                'name' => 'Dinah Lance',
                'codename' => 'Canário Negro',
                'sex' => CharacterSexEnum::FEMALE,
                'age' => '30',
                'avatar' => 'http://myapp.local:8000/storage/public/images/heroes/1721666803.png',
                'affiliate' => 'Oliver Queen',
                'pair' => 'Oliver Queen',
                'planet' => 'Terra',
                'city' => 'Star City',
                'team_id' => 13,
                'squad_id' => null,
                'color' => '#FFD700',
            ]

        ]);
    }
}
